spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chatgptassistant
      username: root
      password: Mtzyh3w4Fp4TZgpG
      authentication-database: admin
      auto-index-creation: true

application:
  openAI:
    key: key-xxxxxxxxxx
